import {
  createContext,
  useContext,
  useMemo,
  useState,
  type ReactNode,
} from "react";
import type { Lang } from "../../types";

const dictionary = {
  ru: {
    // Nav
    home: "Главная",
    map: "Карта",
    museum: "Музей",
    lootbox: "Чүко",
    profile: "Профиль",
    calendar: "Календарь",
    petroQuiz: "Петро Квиз",
    stoneLab: "Каменная лаба",
    gallery: "Галерея",
    leaderboard: "Рейтинг",
    groupExplore: "Исследовать",
    groupPlay: "Играть",
    groupCommunity: "Сообщество",
    account: "Аккаунт",
    menu: "Меню",
    themeLight: "Светлая",
    themeDark: "Тёмная",
    tagline: "Технологии сакральных мест",

    // Map
    scanStone: "Сканировать камень",
    scanStoneDesc: "Пользователь загружает фото, дальше его проверяет админ.",
    selectedPlace: "Выбранное место",
    noPlace: "Выберите объект на карте",
    nearbyWarning: "Вы вошли в охранную зону",
    petroglyphNearby: "Вы рядом с петроглифом: {name}. Можно изучить его, сфотографировать и отправить на проверку.",
    sacredRules: "Правила поведения",
    collect: "Собрать",
    startExploring: "Начать исследование",
    kindSacred: "Сакральное",
    kindPetroglyph: "Петроглиф",
    culturalNote: "Культурная справка",
    analysis: "Анализ",
    source: "Источник",
    openCamera: "Открыть камеру / выбрать фото",
    analyzingPhoto: "Анализируем фото и создаем заявку на модерацию...",
    photoUploaded: "Фото загружено и отправлено на проверку администратору.",
    possiblePetroglyph: "Возможный петроглиф",
    possibleSymbol: "Возможный символ",
    lowConfidence: "Низкая уверенность",
    petroglyphSummary: "Контурные линии напоминают древнюю гравировку. Возможна сцена охоты или изображение животного.",
    symbolSummary: "Обнаружены формы, похожие на символический или сакральный знак. Требуется проверка администратором.",
    lowConfSummary: "Изображение не выглядит как уверенный пример петроглифа. Рекомендуется повторить съемку.",
    userSubmission: "Загрузка пользователя",
    myUploads: "Мои загрузки",
    noUploads: "Пока загрузок нет.",
    uploaded: "Загружено",
    aiMockAnalysis: "ИИ-анализ (мок)",
    possibleInterpretation: "Возможная интерпретация",
    suggestedType: "Предполагаемый тип",
    close: "Закрыть",
    stonePreview: "Предпросмотр камня",
    statusPending: "Ожидает",
    statusApproved: "Одобрено",
    statusRejected: "Отклонено",

    // Home hero
    heroBadge: "Игровая платформа культуры",
    heroTitleLine1: "Исследуй",
    heroTitleLine2: "Кыргызское наследие",
    heroDesc: "Интерактивная платформа, которая делает культуру Кыргызстана интересной через карту, петроглифы, сакральные места, цифровые артефакты и геймификацию.",
    openStoneLab: "Открыть каменную лабу",
    statLevel: "Уровень",
    statPoints: "Очки",
    statArtifacts: "Артефакты",
    mapCardTitle: "Карта",
    mapCardDesc: "Находи сакральные места",
    challengeCardTitle: "Челлендж",
    challengeCardDesc: "Соревнуйся работами",
    playCardTitle: "Играть",
    playCardDesc: "Учись через игру",
    discoverCultureTitle: "Открой культуру",
    discoverCultureDesc: "Изучай сакральные места, петроглифы и культурные объекты на карте.",
    readSymbolsTitle: "Читай символы",
    readSymbolsDesc: "Интерпретируй рисунки, учись читать древние знаки и смыслы.",
    createCompeteTitle: "Создавай и соревнуйся",
    createCompeteDesc: "Создавай свои петроглифы, публикуй их и соревнуйся с другими.",

    // Profile
    profileTitle: "Профиль игрока",
    profileSubtitle: "Уровень, очки, достижения и общий прогресс.",
    xpProgress: "Прогресс XP",
    xpUntilNext: "до следующего уровня",
    achievements: "Достижения",
    noAchievements: "Пока достижений нет. Начни исследование карты и собирай артефакты.",

    // Leaderboard
    leaderboardTitle: "Рейтинг",
    leaderboardSubtitle: "Лучшие работы и авторы сообщества.",
    grandPrize: "Главный приз",
    grandPrizeDesc: "1 место — шанс на физическое воплощение работы и процент от продажи по правилам конкурса",
    topPetroglyphs: "Лучшие петроглифы",
    topArtists: "Лучшие авторы",
    votes: "голосов",
    worksPublished: "опубликованных работ",

    // Community Gallery
    galleryTitle: "Галерея сообщества",
    gallerySubtitle: "Публикуй петроглифы, собирай оценки и соревнуйся с другими авторами.",
    filterAll: "Все",
    rateArtwork: "Оценить работу",
    rating: "Рейтинг",
    voters: "Голосующих",
    byAuthor: "от",
    categoryGoat: "Козёл",
    categoryDeer: "Олень",
    categoryHunter: "Охотник",
    categorySun: "Солнце",
    categoryAbstract: "Абстракция",

    // Lootbox
    lootboxTitle: "Чүко Лутбокс",
    lootboxSubtitle: "Открывай чүко, получай случайные артефакты и усиливай свой цифровой музей.",
    openChuko: "Открыть Чүко",
    opening: "Открывается...",
    dropChances: "Шансы дропа",
    latestReward: "Последняя награда",
    noRewardYet: "Здесь появится результат открытия чүко.",
    duplicateMsg: "Дубликат: артефакт уже есть в коллекции. Начислены очки компенсации.",
    newArtifactMsg: "Новый артефакт добавлен в твой музей.",
    points: "Очки",
    income: "Доход",

    // Museum
    museumTitle: "Цифровой музей",
    museumSubtitle: "Твоя собранная коллекция артефактов.",
    museumEmpty: "Музей пуст",
    museumEmptyDesc: "Пока ты не собрал ни одного артефакта. Перейди на карту или открой чүко.",

    // Quiz
    quizTitle: "Какой ты петроглиф?",
    quizSubtitle: "Тест по мотивам образов кыргызских петроглифов: выбери то, что тебе ближе, и получи свой архетип.",
    quizQuestion: "Вопрос",
    quizOf: "из",
    quizAnalyzing: "Анализируем твой петроглиф...",
    quizAnalyzingDesc: "Архар поднимается по склону, собирает символы и ищет твой архетип среди древних рисунков.",
    quizResult: "Твой результат",
    quizCharacter: "Характер",
    quizWhereTo: "Куда пойти",
    quizRestart: "Пройти ещё раз",

    // Stone Workshop
    stoneWorkshopTitle: "Каменная мастерская",
    stoneWorkshopSubtitle: "Создай свой петроглиф, интерпретируй его и опубликуй в сообществе.",
    carvingMode: "Режим резьбы по камню",
    carvingModeDesc: "Здесь ты не просто рисуешь. Ты словно выбиваешь рисунок на камне: молоток оставляет плотные следы, зубило делает насечки, а мягкий инструмент помогает довести контур.",
    tools: "Инструменты",
    hammer: "Молоток",
    hammerDesc: "Грубые удары по камню",
    chisel: "Зубило",
    chiselDesc: "Точные насечки и форма",
    softTool: "Мягкий инструмент",
    softToolDesc: "Лёгкая проработка линий",
    template: "Шаблон",
    noTemplate: "Без шаблона",
    goat: "Козёл",
    deer: "Олень",
    sunSign: "Солнечный знак",
    hunter: "Охотник",
    actions: "Действия",
    interpretDrawing: "Интерпретировать рисунок",
    clearStone: "Очистить камень",
    savePetroglyph: "Сохранить петроглиф",
    workshopTip: "Совет: начни с шаблона, выбери молоток для грубой формы, потом пройди зубилом по линиям, а в конце используй мягкий инструмент для деталей.",
    interpretation: "Интерпретация",
    whatSystemSaw: "Что система увидела",
    possibleMeaning: "Возможный смысл",
    projection: "Проекция",
    possibleScene: "Возможная сцена",
    mvpNote: "Это предварительная интерпретация для MVP. Она основана на выбранном шаблоне или простой визуальной эвристике.",
    publishToCommunity: "Опубликовать в сообществе",
    publishDesc: "Опубликуй работу, чтобы другие могли её оценивать.",
    workTitle: "Название работы",
    authorName: "Имя автора",
    shortDescription: "Короткое описание работы",
    publishArtwork: "Опубликовать работу",
    firstPlacePrize: "1 место: шанс на физическое воплощение и процент от продажи по правилам конкурса",
    interpretFirst: "Сначала интерпретируй рисунок.",
    fillTitleAuthor: "Заполни название работы и имя автора.",
    artworkPublished: "Работа опубликована в Галерее сообщества.",
    confidenceLow: "низкая",
    confidenceMedium: "средняя",
    confidenceHigh: "высокая",

    // Admin
    adminTitle: "Проверка заявок",
    adminSubtitle: "Проверка пользовательских находок перед публикацией на карте.",
    noPending: "Нет заявок на проверке.",
    approve: "Одобрить",
    reject: "Отклонить",

    // Calendar
    calendarTitle: "Кыргызский календарь",
    calendarSubtitle: "Привычный календарь + кыргызские названия месяцев + интерактивное обучение.",
    calendarView: "Просмотр календаря",
    selectedDate: "Выбранная дата",
    easyExplanation: "Простое объяснение",
    guideTitle: "Руководство по календарю",
    glossaryTitle: "Словарь",
    learnPlay: "Учись и играй",
    learnPlayDesc: "Угадай кыргызское название месяца и запоминай через игру.",
    russianMonth: "Русский месяц",
    score: "Счёт",
    streak: "Серия",
    correctAnswer: "Правильный ответ",
    nextRound: "Следующий раунд",
    today: "Сегодня",
    simply: "Просто:",
    wheelTitle: "Круговой календарь",
    wheelDesc: "Визуализация года в форме кругового календаря: месяцы, кыргызские названия и сезонные периоды чилде.",
    kyrgyzCalendar: "КЫРГЫЗ КАЛЕНДАРЬ",
    legendKyshChilde: "Кыш чилде",
    legendZhayChilde: "Жай чилде",
    legendTokson: "Токсон",

    // Map page
    mapTitle: "Карта сакральных мест и петроглифов",
    mapSubtitle: "Карта для туристов, местных жителей и семейных поездок: укажи точку A и точку B, а система сама предложит культурные места по пути.",
    tripPlanner: "Планировщик маршрута",
    tripPlannerDesc: "Выбери точку A и точку B, а затем построй путь вручную или автоматически.",
    pointA: "Точка A",
    pointB: "Точка B",
    myLocation: "Моя локация",
    chooseLocation: "Выбрать место",
    selectPointA: "Выберите точку A",
    selectPointB: "Выберите точку B",
    stopsOnWay: "Остановки по пути",
    stopsHint: "Нажмите «Добавить в маршрут» или используйте авто-маршрут",
    noStops: "Остановок пока нет",
    remove: "Удалить",
    buildManually: "Построить вручную",
    buildAuto: "Создать маршрут автоматически",
    clear: "Очистить",
    suggestedStops: "Предложенные культуральные остановки",
    routeSummary: "Сводка маршрута",
    routeStart: "Начало",
    routeDestination: "Назначение",
    routeStops: "Остановки",
    routeDistance: "Примерное расстояние",
    addToRoute: "Добавить в маршрут",
  },

  en: {
    // Nav
    home: "Home",
    map: "Map",
    museum: "Museum",
    lootbox: "Chüko",
    profile: "Profile",
    calendar: "Calendar",
    petroQuiz: "Petro Quiz",
    stoneLab: "Stone Lab",
    gallery: "Gallery",
    leaderboard: "Leaderboard",
    groupExplore: "Explore",
    groupPlay: "Play",
    groupCommunity: "Community",
    account: "Account",
    menu: "Menu",
    themeLight: "Light",
    themeDark: "Dark",
    tagline: "Sacred Tech Platform",

    // Map
    scanStone: "Scan stone",
    scanStoneDesc: "User uploads a photo, then admin reviews it.",
    selectedPlace: "Selected place",
    noPlace: "Select a place on the map",
    nearbyWarning: "You entered a protected zone",
    petroglyphNearby: "You are near a petroglyph: {name}. You can study it, photograph it and submit for review.",
    sacredRules: "Respect guidelines",
    collect: "Collect",
    startExploring: "Start exploring",
    kindSacred: "Sacred",
    kindPetroglyph: "Petroglyph",
    culturalNote: "Cultural note",
    analysis: "Analysis",
    source: "Source",
    openCamera: "Open camera / select photo",
    analyzingPhoto: "Analyzing photo and creating moderation request...",
    photoUploaded: "Photo uploaded and sent to admin review.",
    possiblePetroglyph: "Possible petroglyph",
    possibleSymbol: "Possible symbol",
    lowConfidence: "Low confidence",
    petroglyphSummary: "Contour lines resemble an ancient engraving. Possibly a hunting scene or an animal depiction.",
    symbolSummary: "Forms resembling a symbolic or sacred sign were detected. Admin verification required.",
    lowConfSummary: "The image does not look like a confident petroglyph example. Re-shooting is recommended.",
    userSubmission: "User submission",
    myUploads: "My Uploads",
    noUploads: "No uploads yet.",
    uploaded: "Uploaded",
    aiMockAnalysis: "AI mock analysis",
    possibleInterpretation: "Possible interpretation",
    suggestedType: "Suggested type",
    close: "Close",
    stonePreview: "Stone preview",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",

    // Home hero
    heroBadge: "Cultural gaming platform",
    heroTitleLine1: "Explore",
    heroTitleLine2: "Kyrgyz Heritage",
    heroDesc: "An interactive platform that makes Kyrgyz culture engaging through maps, petroglyphs, sacred sites, digital artifacts and gamification.",
    openStoneLab: "Open Stone Lab",
    statLevel: "Level",
    statPoints: "Points",
    statArtifacts: "Artifacts",
    mapCardTitle: "Map",
    mapCardDesc: "Discover sacred places",
    challengeCardTitle: "Challenge",
    challengeCardDesc: "Compete with artworks",
    playCardTitle: "Play",
    playCardDesc: "Learn through interaction",
    discoverCultureTitle: "Discover Culture",
    discoverCultureDesc: "Explore sacred sites, petroglyphs and cultural landmarks on the map.",
    readSymbolsTitle: "Read the Symbols",
    readSymbolsDesc: "Interpret ancient drawings and learn to read their meaning.",
    createCompeteTitle: "Create & Compete",
    createCompeteDesc: "Create your own petroglyphs, publish them and compete with others.",

    // Profile
    profileTitle: "Player Profile",
    profileSubtitle: "Level, points, achievements and overall progress.",
    xpProgress: "XP Progress",
    xpUntilNext: "until next level",
    achievements: "Achievements",
    noAchievements: "No achievements yet. Start exploring the map and collect artifacts.",

    // Leaderboard
    leaderboardTitle: "Leaderboard",
    leaderboardSubtitle: "Top artworks and artists of the community.",
    grandPrize: "Grand Prize",
    grandPrizeDesc: "1st place — chance for physical realization of the work and a share of sales per contest rules",
    topPetroglyphs: "Top Petroglyphs",
    topArtists: "Top Artists",
    votes: "votes",
    worksPublished: "works published",

    // Community Gallery
    galleryTitle: "Community Gallery",
    gallerySubtitle: "Publish petroglyphs, collect ratings and compete with other authors.",
    filterAll: "All",
    rateArtwork: "Rate this artwork",
    rating: "Rating",
    voters: "Voters",
    byAuthor: "by",
    categoryGoat: "Goat",
    categoryDeer: "Deer",
    categoryHunter: "Hunter",
    categorySun: "Sun",
    categoryAbstract: "Abstract",

    // Lootbox
    lootboxTitle: "Chüko Lootbox",
    lootboxSubtitle: "Open chüko boxes, collect random artifacts and power up your digital museum.",
    openChuko: "Open Chuko",
    opening: "Opening...",
    dropChances: "Drop Chances",
    latestReward: "Latest Reward",
    noRewardYet: "Your lootbox result will appear here.",
    duplicateMsg: "Duplicate item: artifact already in collection. Compensation points added.",
    newArtifactMsg: "New artifact collected and added to your museum.",
    points: "Points",
    income: "Income",

    // Museum
    museumTitle: "Digital Museum",
    museumSubtitle: "Your collected artifact collection.",
    museumEmpty: "Museum is empty",
    museumEmptyDesc: "You haven't collected any artifacts yet. Head to the map or open a chüko.",

    // Quiz
    quizTitle: "Which petroglyph are you?",
    quizSubtitle: "A quiz based on Kyrgyz petroglyph motifs: choose what resonates and get your archetype.",
    quizQuestion: "Question",
    quizOf: "of",
    quizAnalyzing: "Analyzing your petroglyph...",
    quizAnalyzingDesc: "The Arkhar climbs the slope, gathering symbols to find your archetype among ancient drawings.",
    quizResult: "Your result",
    quizCharacter: "Character",
    quizWhereTo: "Where to go",
    quizRestart: "Take again",

    // Stone Workshop
    stoneWorkshopTitle: "Stone Workshop",
    stoneWorkshopSubtitle: "Create your own petroglyph, interpret it and publish to the community.",
    carvingMode: "Stone carving mode",
    carvingModeDesc: "Here you don't just draw. You carve the design onto stone: the hammer leaves dense marks, the chisel makes notches, and the soft tool helps refine the outline.",
    tools: "Tools",
    hammer: "Hammer",
    hammerDesc: "Rough strikes on stone",
    chisel: "Chisel",
    chiselDesc: "Precise notches and shape",
    softTool: "Soft tool",
    softToolDesc: "Light line work",
    template: "Template",
    noTemplate: "No template",
    goat: "Goat",
    deer: "Deer",
    sunSign: "Sun sign",
    hunter: "Hunter",
    actions: "Actions",
    interpretDrawing: "Interpret drawing",
    clearStone: "Clear stone",
    savePetroglyph: "Save petroglyph",
    workshopTip: "Tip: start with a template, use the hammer for rough shape, then run the chisel along the lines, and finish with the soft tool for details.",
    interpretation: "Interpretation",
    whatSystemSaw: "What the system saw",
    possibleMeaning: "Possible meaning",
    projection: "Projection",
    possibleScene: "Possible scene",
    mvpNote: "This is a preliminary interpretation for the MVP. It is based on the chosen template or simple visual heuristics.",
    publishToCommunity: "Publish to Community",
    publishDesc: "Publish your work so others can rate it.",
    workTitle: "Artwork title",
    authorName: "Author name",
    shortDescription: "Short description",
    publishArtwork: "Publish artwork",
    firstPlacePrize: "1st place: chance for physical realization and a share of sales per contest rules",
    interpretFirst: "Interpret the drawing first.",
    fillTitleAuthor: "Fill in the artwork title and author name.",
    artworkPublished: "Artwork published to the Community Gallery.",
    confidenceLow: "low",
    confidenceMedium: "medium",
    confidenceHigh: "high",

    // Admin
    adminTitle: "Admin Review",
    adminSubtitle: "Review user submissions before publishing on the map.",
    noPending: "No pending submissions.",
    approve: "Approve",
    reject: "Reject",

    // Calendar
    calendarTitle: "Kyrgyz Sky Calendar",
    calendarSubtitle: "Regular calendar + Kyrgyz month names + interactive learning.",
    calendarView: "Calendar view",
    selectedDate: "Selected date",
    easyExplanation: "Easy explanation",
    guideTitle: "Guide to the calendar",
    glossaryTitle: "Glossary",
    learnPlay: "Learn & Play",
    learnPlayDesc: "Guess the Kyrgyz month name and learn through play.",
    russianMonth: "Russian month",
    score: "Score",
    streak: "Streak",
    correctAnswer: "Correct answer",
    nextRound: "Next round",
    today: "Today",
    simply: "Simply:",
    wheelTitle: "Circular calendar",
    wheelDesc: "Visualization of the year as a circular calendar: months, Kyrgyz names and seasonal childe periods.",
    kyrgyzCalendar: "KYRGYZ CALENDAR",
    legendKyshChilde: "Kysh childe",
    legendZhayChilde: "Zhay childe",
    legendTokson: "Tokson",

    // Map page
    mapTitle: "Sacred & Rock Art Map",
    mapSubtitle: "A map for tourists, locals and family trips: set point A and point B, and the system suggests cultural stops along the way.",
    tripPlanner: "Trip Planner",
    tripPlannerDesc: "Choose point A and point B, then build your route manually or automatically.",
    pointA: "Point A",
    pointB: "Point B",
    myLocation: "My location",
    chooseLocation: "Choose location",
    selectPointA: "Select point A",
    selectPointB: "Select point B",
    stopsOnWay: "Stops on the way",
    stopsHint: "Click \"Add to route\" or use auto route",
    noStops: "No stops added yet",
    remove: "Remove",
    buildManually: "Build manually",
    buildAuto: "Create route automatically",
    clear: "Clear",
    suggestedStops: "Suggested cultural stops",
    routeSummary: "Route summary",
    routeStart: "Start",
    routeDestination: "Destination",
    routeStops: "Stops",
    routeDistance: "Estimated distance",
    addToRoute: "Add to route",
  },
} as const;

type LanguageContextType = {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: typeof dictionary['ru'] | typeof dictionary['en'];
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = window.localStorage.getItem("lang");
    return stored === "en" ? "en" : "ru";
  });

  const setLang = (next: Lang) => {
    setLangState(next);
    window.localStorage.setItem("lang", next);
  };

  const value = useMemo(
    () => ({
      lang,
      setLang,
      t: dictionary[lang],
    }),
    [lang],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
